### ISSUE TITLE
Is batch processing possible during inference?

### ISSUE THREAD

**Issue by ereday** [RUCAIBox/MVP#7]
Hi, thank you for providing a pre-trained model. I am wondering if it is possible to perform a batched prediction with the model at https://huggingface.co/RUCAIBox/mtl-data-to-text ? Something like below?:

```
inputs = tokenizer(
    ["Describe the following data: Iron Man | instance of | Superhero [SEP] Stan Lee | creator | Iron Man",
     "Describe the following data: Batman | instance of | Superhero",
    ]
    return_tensors="pt",
)

generated_ids = model.generate(**inputs)

tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
['Iron Man is a fictional superhero appearing in American comic books published by Marvel Comics.',
"Batman is a superhero"]

```

**Comment by StevenTang1998** [comment]
Sorry, I am a little confused about your requirements. Does this code have an issue and does not solve the batch prediction?

**Comment by ereday** [comment]
Ah, sorry for the confusion. I was wondering how I can use the pre-trained model with batch sizes bigger than 1. As an example, let's say I have these two texts as input:

```
t1='Describe the following data: Love Is Mighty Close | INSTANCE_OF | album [SEP]'
t2='Describe the following data: Iron Man | instance of | Superhero [SEP] Stan Lee | creator | Iron Man'

```

And I'd like to make MTL-data-to-text model describe both t1 and t2 at the same time instead of running the forward pass twice as shown below:
```

tokenizer = MvpTokenizer.from_pretrained("RUCAIBox/mvp")
model = MvpForConditionalGeneration.from_pretrained("RUCAIBox/mtl-data-to-text")
# T1
inputs = tokenizer(t1, return_tensors="pt")
generated_ids = model.generate(**inputs)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
# T2
inputs = tokenizer(t2, return_tensors="pt")
generated_ids = model.generate(**inputs)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
```

Does the current codebase support inferencing with bs>1?

**Comment by StevenTang1998** [comment]
```python
inputs = tokenizer([t1, t2], return_tensors="pt")
generated_ids = model.generate(**inputs)
tokenizer.batch_decode(generated_ids, skip_special_tokens=True)
```
Does this satisfy your requirements?

**Comment by ereday** [comment]
Thanks for reply. I've tried what you shared above. It throws this error:

```
>>> inputs = tokenizer([t1, t2], return_tensors="pt")
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 717, in convert_to_tensors
    tensor = as_tensor(value)
ValueError: expected sequence of length 20 at dim 1 (got 24)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2520, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2606, in _call_one
    return self.batch_encode_plus(
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2797, in batch_encode_plus
    return self._batch_encode_plus(
  File "/opt/conda/envs/py38_/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 737, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/opt/conda/envs/py38_/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 817, in _batch_prepare_for_model
    batch_outputs = BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/opt/conda/envs/py38_/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 210, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/opt/conda/envs/py38_/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 733, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
```

**Comment by ereday** [comment]
Yes, it works. Oddly enough, I tried this before I created the issue, but it didn't work then. Anyway, thank you. I'm closing the issue.
